apiVersion: batch/v1
kind: Job
metadata:
  name: proglog
spec:
  template:
    metadata:
      name: proglog
    spec:
      containers:
      - name: proglog
        image: github.com/rezaamiri123/proglog:0.0.1
        imagePullPolicy: Never
      restartPolicy: Never
